import { Product, Giveaway } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 1,
    cat: 'handgun',
    name: 'Glock 19 Gen 5',
    brand: 'Glock',
    caliber: '9mm Luger',
    capacity: '15+1',
    upc: '764503030100',
    restrictions: {
      CA: 'Not on approved handgun roster — cannot be sold new in CA',
      NY: 'Pistol permit required before purchase',
      MD: 'Handgun Qualification License required before purchase',
      MA: 'Not on approved handgun roster',
      HI: 'Registration required within 5 days of acquisition',
    },
    listings: [
      { retailer: 'GunBroker', price: 455, stock: 'in', financing: false, url: 'https://www.gunbroker.com/pistols/search#keywords=glock+19+gen+5' },
      { retailer: "Bud's Gun Shop", price: 489, stock: 'in', financing: true, url: 'https://www.budsgunshop.com/catalog/index.php/cPath/36/manufacturers_id/2?filter_cat=Pistols&filter_model=G19' },
      { retailer: 'Guns.com', price: 499, stock: 'in', financing: true, url: 'https://guns.com/search?query=glock+19+gen+5' },
      { retailer: 'GrabAGun', price: 509, stock: 'low', financing: false, url: 'https://www.grabaggun.com/search?q=glock+19+gen+5' },
      { retailer: 'Palmetto State Armory', price: 519, stock: 'in', financing: true, url: 'https://palmettostatearmory.com/handguns/glock.html' },
    ],
    localDealers: [
      { name: 'RTSP Maryland', distance: '3.2 mi', stock: 'In stock', price: 524, phone: '(443) 832-6900', address: '9 Bata Blvd, Belcamp, MD' },
      { name: 'Engage Armament', distance: '5.8 mi', stock: 'Call ahead', price: null, phone: '(301) 990-9468', address: '806 Rockville Pike, Rockville, MD' },
      { name: 'Maryland Small Arms Range', distance: '9.1 mi', stock: 'In stock', price: 509, phone: '(301) 948-9160', address: '9630 Darnestown Rd, Gaithersburg, MD' },
    ],
    priceHistory: [499, 510, 505, 492, 480, 472, 455],
    allTimeLow: 424,
    hotDeal: true,
    tags: ['Best seller', 'Compact'],
  },
  {
    id: 2,
    cat: 'handgun',
    name: 'SIG Sauer P320 M17',
    brand: 'SIG Sauer',
    caliber: '9mm Luger',
    capacity: '17+1',
    restrictions: {
      NY: 'Pistol permit required before purchase',
      MD: 'Handgun Qualification License required before purchase',
      MA: 'Not on approved handgun roster',
      CA: 'Not on approved handgun roster — cannot be sold new in CA',
    },
    listings: [
      { retailer: 'GunBroker', price: 499, stock: 'in', financing: false, url: 'https://www.gunbroker.com/pistols/search#keywords=sig+p320+m17' },
      { retailer: "Bud's Gun Shop", price: 529, stock: 'in', financing: true, url: 'https://www.budsgunshop.com' },
      { retailer: 'Guns.com', price: 549, stock: 'low', financing: true, url: 'https://guns.com' },
      { retailer: 'Palmetto State Armory', price: 559, stock: 'in', financing: true, url: 'https://palmettostatearmory.com' },
    ],
    localDealers: [
      { name: 'Engage Armament', distance: '5.8 mi', stock: 'In stock', price: 579, phone: '(301) 990-9468', address: '806 Rockville Pike, Rockville, MD' },
      { name: 'RTSP Maryland', distance: '3.2 mi', stock: 'Call ahead', price: null, phone: '(443) 832-6900', address: '9 Bata Blvd, Belcamp, MD' },
    ],
    priceHistory: [579, 569, 559, 549, 539, 529, 499],
    allTimeLow: 479,
    hotDeal: true,
    tags: ['Military adoption', 'Full-size'],
  },
  {
    id: 3,
    cat: 'rifle',
    name: 'S&W M&P15 Sport II',
    brand: 'Smith & Wesson',
    caliber: '5.56 NATO / .223 Rem',
    capacity: '30+1',
    restrictions: {
      CA: 'Assault Weapons Ban — prohibited configuration. Featureless build required.',
      NY: 'SAFE Act — prohibited configuration',
      MD: 'Assault Weapons Ban — prohibited',
      MA: 'Assault Weapons Ban — prohibited',
      CT: 'Assault Weapons Ban — prohibited',
      NJ: 'Assault Weapons Ban — prohibited',
      HI: '10-round magazine limit applies',
      CO: '15-round magazine limit applies',
    },
    listings: [
      { retailer: 'GunBroker', price: 599, stock: 'in', financing: false, url: 'https://www.gunbroker.com/rifles/search#keywords=mp15+sport+ii' },
      { retailer: 'Palmetto State Armory', price: 649, stock: 'in', financing: true, url: 'https://palmettostatearmory.com/rifles.html' },
      { retailer: 'Guns.com', price: 669, stock: 'oos', financing: true, url: 'https://guns.com' },
      { retailer: "Bud's Gun Shop", price: 679, stock: 'low', financing: false, url: 'https://www.budsgunshop.com' },
    ],
    localDealers: [
      { name: 'Nova Firearms', distance: '4.1 mi', stock: 'In stock', price: 699, phone: '(703) 241-6800', address: 'McLean, VA' },
      { name: 'Blue Ridge Arsenal', distance: '7.3 mi', stock: 'In stock', price: 679, phone: '(703) 378-4867', address: 'Chantilly, VA' },
    ],
    priceHistory: [699, 719, 699, 679, 665, 649, 599],
    allTimeLow: 579,
    hotDeal: false,
    tags: ['AR-15', 'Most popular'],
  },
  {
    id: 4,
    cat: 'shotgun',
    name: 'Mossberg 500 All-Purpose',
    brand: 'Mossberg',
    caliber: '12 Gauge',
    capacity: '5+1',
    restrictions: {
      CA: '10-round limit does not apply to most shotgun configs',
    },
    listings: [
      { retailer: 'GunBroker', price: 340, stock: 'low', financing: false, url: 'https://www.gunbroker.com/shotguns/search#keywords=mossberg+500' },
      { retailer: "Bud's Gun Shop", price: 359, stock: 'in', financing: true, url: 'https://www.budsgunshop.com' },
      { retailer: 'GrabAGun', price: 369, stock: 'in', financing: false, url: 'https://www.grabaggun.com' },
      { retailer: "Sportsman's Warehouse", price: 379, stock: 'in', financing: true, url: 'https://www.sportsmanswarehouse.com' },
    ],
    localDealers: [
      { name: 'RTSP Maryland', distance: '3.2 mi', stock: 'In stock', price: 389, phone: '(443) 832-6900', address: '9 Bata Blvd, Belcamp, MD' },
      { name: 'Maryland Small Arms Range', distance: '9.1 mi', stock: 'In stock', price: 375, phone: '(301) 948-9160', address: '9630 Darnestown Rd, Gaithersburg, MD' },
    ],
    priceHistory: [389, 399, 389, 375, 365, 359, 340],
    allTimeLow: 319,
    hotDeal: true,
    tags: ['Home defense', 'Hunting'],
  },
  {
    id: 5,
    cat: 'rifle',
    name: 'Ruger 10/22 Carbine',
    brand: 'Ruger',
    caliber: '.22 LR',
    capacity: '10+1',
    restrictions: {
      CA: 'Compliant — magazine limit does not restrict standard config',
    },
    listings: [
      { retailer: 'GunBroker', price: 249, stock: 'in', financing: false, url: 'https://www.gunbroker.com/rifles/search#keywords=ruger+1022' },
      { retailer: "Bud's Gun Shop", price: 269, stock: 'in', financing: true, url: 'https://www.budsgunshop.com' },
      { retailer: 'Guns.com', price: 279, stock: 'in', financing: false, url: 'https://guns.com' },
      { retailer: "Sportsman's Warehouse", price: 289, stock: 'in', financing: true, url: 'https://www.sportsmanswarehouse.com' },
    ],
    localDealers: [
      { name: 'RTSP Maryland', distance: '3.2 mi', stock: 'In stock', price: 299, phone: '(443) 832-6900', address: '9 Bata Blvd, Belcamp, MD' },
      { name: 'Nova Firearms', distance: '4.1 mi', stock: 'In stock', price: 289, phone: '(703) 241-6800', address: 'McLean, VA' },
    ],
    priceHistory: [299, 289, 289, 279, 275, 269, 249],
    allTimeLow: 239,
    hotDeal: false,
    tags: ['Rimfire', 'Beginner friendly'],
  },
  {
    id: 6,
    cat: 'ammo',
    name: 'Federal AE 9mm 124gr FMJ — 1000 rounds',
    brand: 'Federal',
    caliber: '9mm Luger',
    capacity: '1000 rds',
    restrictions: {
      CA: 'Must ship to a licensed ammunition vendor — cannot ship direct',
      NY: 'Background check required for ammo purchases',
      IL: 'FOID card required for purchase',
    },
    listings: [
      { retailer: 'GunBroker', price: 209, stock: 'in', financing: false, url: 'https://www.gunbroker.com/ammunition/search#keywords=federal+ae+9mm+1000' },
      { retailer: 'Palmetto State Armory', price: 219, stock: 'in', financing: false, url: 'https://palmettostatearmory.com/ammunition.html' },
      { retailer: "Bud's Gun Shop", price: 224, stock: 'low', financing: false, url: 'https://www.budsgunshop.com' },
      { retailer: 'GrabAGun', price: 229, stock: 'in', financing: false, url: 'https://www.grabaggun.com' },
    ],
    localDealers: [
      { name: 'Local Ammo & Range', distance: '1.9 mi', stock: 'In stock', price: 249, phone: '(240) 555-0190', address: 'Bethesda, MD' },
      { name: 'RTSP Maryland', distance: '3.2 mi', stock: 'Limited', price: 239, phone: '(443) 832-6900', address: '9 Bata Blvd, Belcamp, MD' },
    ],
    priceHistory: [249, 239, 235, 229, 224, 219, 209],
    allTimeLow: 189,
    hotDeal: false,
    tags: ['Range ammo', 'Bulk'],
  },
  {
    id: 7,
    cat: 'ammo',
    name: 'Hornady Critical Defense .380 ACP 90gr FTX — 25 rounds',
    brand: 'Hornady',
    caliber: '.380 ACP',
    capacity: '25 rds',
    restrictions: {
      CA: 'Must ship to a licensed ammunition vendor',
      NY: 'Background check required',
      NJ: 'Hollow point restrictions in some counties',
    },
    listings: [
      { retailer: "Bud's Gun Shop", price: 24, stock: 'in', financing: false, url: 'https://www.budsgunshop.com' },
      { retailer: 'GrabAGun', price: 26, stock: 'in', financing: false, url: 'https://www.grabaggun.com' },
      { retailer: 'Guns.com', price: 27, stock: 'low', financing: false, url: 'https://guns.com' },
      { retailer: 'Palmetto State Armory', price: 28, stock: 'in', financing: false, url: 'https://palmettostatearmory.com' },
    ],
    localDealers: [
      { name: 'Engage Armament', distance: '5.8 mi', stock: 'In stock', price: 31, phone: '(301) 990-9468', address: '806 Rockville Pike, Rockville, MD' },
    ],
    priceHistory: [32, 30, 29, 27, 26, 25, 24],
    allTimeLow: 22,
    hotDeal: false,
    tags: ['Defensive', 'JHP'],
  },
  {
    id: 8,
    cat: 'parts',
    name: 'Holosun HS507C X2 Red Dot',
    brand: 'Holosun',
    caliber: 'N/A',
    capacity: 'N/A',
    restrictions: {},
    listings: [
      { retailer: 'Palmetto State Armory', price: 259, stock: 'in', financing: true, url: 'https://palmettostatearmory.com/optics.html' },
      { retailer: 'GrabAGun', price: 269, stock: 'in', financing: false, url: 'https://www.grabaggun.com' },
      { retailer: "Bud's Gun Shop", price: 279, stock: 'in', financing: true, url: 'https://www.budsgunshop.com' },
      { retailer: 'Brownells', price: 289, stock: 'low', financing: false, url: 'https://www.brownells.com' },
    ],
    localDealers: [
      { name: 'Engage Armament', distance: '5.8 mi', stock: 'In stock', price: 295, phone: '(301) 990-9468', address: '806 Rockville Pike, Rockville, MD' },
    ],
    priceHistory: [319, 309, 299, 289, 279, 269, 259],
    allTimeLow: 239,
    hotDeal: true,
    tags: ['Optic', 'Solar'],
  },
  {
    id: 9,
    cat: 'parts',
    name: 'Magpul MOE AR-15 Stock — Mil-Spec',
    brand: 'Magpul',
    caliber: 'N/A',
    capacity: 'N/A',
    restrictions: {
      CA: 'Featureless build requires fixed stock — collapsible stock prohibited',
      NY: 'Collapsible stock prohibited on semi-auto rifles',
      MD: 'Collapsible stock prohibited on regulated firearms',
      MA: 'Collapsible stock prohibited on assault weapons',
    },
    listings: [
      { retailer: 'Palmetto State Armory', price: 49, stock: 'in', financing: false, url: 'https://palmettostatearmory.com' },
      { retailer: 'Brownells', price: 54, stock: 'in', financing: false, url: 'https://www.brownells.com' },
      { retailer: 'GrabAGun', price: 57, stock: 'in', financing: false, url: 'https://www.grabaggun.com' },
    ],
    localDealers: [
      { name: 'Blue Ridge Arsenal', distance: '7.3 mi', stock: 'In stock', price: 64, phone: '(703) 378-4867', address: 'Chantilly, VA' },
    ],
    priceHistory: [64, 59, 57, 54, 52, 50, 49],
    allTimeLow: 44,
    hotDeal: false,
    tags: ['Stock', 'AR-15'],
  },
];

export const GIVEAWAYS: Giveaway[] = [
  {
    id: 1,
    title: 'Glock 19 Gen 5 + 500 rounds',
    prize: 'Glock 19 Gen 5 + 500rds Federal 9mm',
    endsAt: '2026-06-30',
    entryUrl: '#giveaway',
  },
  {
    id: 2,
    title: 'Holosun HS507C optic giveaway',
    prize: 'Holosun HS507C X2 Red Dot',
    endsAt: '2026-07-15',
    entryUrl: '#giveaway',
  },
];
