import { StateCode, StateInfo, StateRestrictionLevel } from './types';

export const STATE_DATA: Record<StateCode, StateInfo> = {
  AL: { name: 'Alabama', level: 'permissive', notes: ['No permit to purchase', 'Permitless carry'] },
  AK: { name: 'Alaska', level: 'permissive', notes: ['No permit to purchase', 'Permitless carry'] },
  AZ: { name: 'Arizona', level: 'permissive', notes: ['No permit to purchase', 'Permitless carry'] },
  AR: { name: 'Arkansas', level: 'permissive', notes: ['No permit to purchase', 'Permitless carry'] },
  CA: { name: 'California', level: 'restricted', notes: ['Handgun Roster required', '10-round magazine limit', 'Assault Weapons Ban', '10-day waiting period', 'Ammo must ship to licensed vendor'] },
  CO: { name: 'Colorado', level: 'standard', notes: ['No permit to purchase', 'Background check required', '15-round magazine limit'] },
  CT: { name: 'Connecticut', level: 'regulated', notes: ['Permit to purchase handguns', '10-round magazine limit', 'Assault Weapons Ban'] },
  DE: { name: 'Delaware', level: 'standard', notes: ['No permit to purchase', 'Background check required'] },
  FL: { name: 'Florida', level: 'standard', notes: ['No permit to purchase', '3-day waiting period on handguns'] },
  GA: { name: 'Georgia', level: 'permissive', notes: ['No permit to purchase', 'Permitless carry'] },
  HI: { name: 'Hawaii', level: 'restricted', notes: ['Permit to purchase required', 'Registration required', '10-round magazine limit'] },
  ID: { name: 'Idaho', level: 'permissive', notes: ['No permit to purchase', 'Permitless carry'] },
  IL: { name: 'Illinois', level: 'regulated', notes: ['FOID card required', '72-hour waiting period', '10-round magazine limit in some jurisdictions'] },
  IN: { name: 'Indiana', level: 'permissive', notes: ['No permit to purchase', 'Permitless carry'] },
  IA: { name: 'Iowa', level: 'permissive', notes: ['No permit to purchase', 'Permitless carry'] },
  KS: { name: 'Kansas', level: 'permissive', notes: ['No permit to purchase', 'Permitless carry'] },
  KY: { name: 'Kentucky', level: 'permissive', notes: ['No permit to purchase', 'Permitless carry'] },
  LA: { name: 'Louisiana', level: 'permissive', notes: ['No permit to purchase', 'Permitless carry'] },
  ME: { name: 'Maine', level: 'permissive', notes: ['No permit to purchase', 'Permitless carry'] },
  MD: { name: 'Maryland', level: 'regulated', notes: ['Handgun Qualification License required', '10-round magazine limit', 'Assault Weapons Ban', '7-day waiting period'] },
  MA: { name: 'Massachusetts', level: 'restricted', notes: ['LTC or FID required', 'Approved handgun roster', '10-round magazine limit', 'Assault Weapons Ban'] },
  MI: { name: 'Michigan', level: 'standard', notes: ['Pistol purchase permit for handguns', 'Background check required'] },
  MN: { name: 'Minnesota', level: 'standard', notes: ['Permit to purchase handguns', 'Background check required'] },
  MS: { name: 'Mississippi', level: 'permissive', notes: ['No permit to purchase', 'Permitless carry'] },
  MO: { name: 'Missouri', level: 'permissive', notes: ['No permit to purchase', 'Permitless carry'] },
  MT: { name: 'Montana', level: 'permissive', notes: ['No permit to purchase', 'Permitless carry'] },
  NE: { name: 'Nebraska', level: 'standard', notes: ['Handgun certificate required', 'Background check required'] },
  NV: { name: 'Nevada', level: 'standard', notes: ['No permit to purchase', 'Background check at all sales'] },
  NH: { name: 'New Hampshire', level: 'permissive', notes: ['No permit to purchase', 'Permitless carry'] },
  NJ: { name: 'New Jersey', level: 'restricted', notes: ['Permit to purchase handguns', 'FID card for long guns', '10-round magazine limit', 'Assault Weapons Ban'] },
  NM: { name: 'New Mexico', level: 'standard', notes: ['No permit to purchase', 'Background check required'] },
  NY: { name: 'New York', level: 'restricted', notes: ['Pistol permit required', '10-round magazine limit', 'SAFE Act Assault Weapons Ban', 'Ammo background check required'] },
  NC: { name: 'North Carolina', level: 'standard', notes: ['Permit to purchase handguns', 'Background check required'] },
  ND: { name: 'North Dakota', level: 'permissive', notes: ['No permit to purchase', 'Permitless carry'] },
  OH: { name: 'Ohio', level: 'permissive', notes: ['No permit to purchase', 'Permitless carry'] },
  OK: { name: 'Oklahoma', level: 'permissive', notes: ['No permit to purchase', 'Permitless carry'] },
  OR: { name: 'Oregon', level: 'regulated', notes: ['Enhanced background check', 'Permit to purchase required', '10-round magazine limit'] },
  PA: { name: 'Pennsylvania', level: 'standard', notes: ['No permit to purchase', 'Background check required'] },
  RI: { name: 'Rhode Island', level: 'regulated', notes: ['Safety certificate required', '7-day waiting period', '10-round magazine limit'] },
  SC: { name: 'South Carolina', level: 'permissive', notes: ['No permit to purchase', 'Permitless carry'] },
  SD: { name: 'South Dakota', level: 'permissive', notes: ['No permit to purchase', 'Permitless carry'] },
  TN: { name: 'Tennessee', level: 'permissive', notes: ['No permit to purchase', 'Permitless carry'] },
  TX: { name: 'Texas', level: 'permissive', notes: ['No permit to purchase', 'Permitless carry (LTC optional)'] },
  UT: { name: 'Utah', level: 'permissive', notes: ['No permit to purchase', 'Permitless carry'] },
  VT: { name: 'Vermont', level: 'standard', notes: ['No permit to purchase', 'Permitless carry', '10-round pistol / 15-round rifle magazine limit'] },
  VA: { name: 'Virginia', level: 'standard', notes: ['No permit to purchase', 'Background check required', 'One handgun per 30 days'] },
  WA: { name: 'Washington', level: 'regulated', notes: ['Enhanced background check', '10-day waiting period', 'Semi-auto assault rifle restrictions'] },
  WV: { name: 'West Virginia', level: 'permissive', notes: ['No permit to purchase', 'Permitless carry'] },
  WI: { name: 'Wisconsin', level: 'standard', notes: ['No permit to purchase', 'Background check required'] },
  WY: { name: 'Wyoming', level: 'permissive', notes: ['No permit to purchase', 'Permitless carry'] },
};

export const LEVEL_LABELS: Record<StateRestrictionLevel, string> = {
  permissive: 'Permissive',
  standard: 'Standard',
  regulated: 'Regulated',
  restricted: 'Highly restricted',
};
